version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
      - vscode-server:/home/node/.vscode-server
      - vscode-server-insiders:/home/node/.vscode-server-insiders # And/or for VS Code Insiders
    command: sleep infinity

volumes:
  vscode-server:
  vscode-server-insiders:
